// --- BEGIN GENERATED API REGISTRY ---
// This section is auto-generated by scripts/update-api-registry.mjs
// /api/auth
import type * as AuthLoginRoute from "@/app/api/auth/login/route";

// /api/checkin
import type * as CheckinVerifyRoute from "@/app/api/checkin/verify/route";

// /api/extreme
import type * as ExtremeOrgIdProjectsProjectIdTasksCatchallRoute from "@/app/api/extreme/[orgId]/projects/[projectId]/tasks/[...catchall]/route";
import type * as ExtremeComplexTypesRoute from "@/app/api/extreme/complex-types/route";
import type * as ExtremeMethodsRoute from "@/app/api/extreme/methods/route";

// /api/orders
import type * as OrdersCheckoutRoute from "@/app/api/orders/checkout/route";

// /api/system
import type * as SystemHealthRoute from "@/app/api/system/health/route";

// /api/users
import type * as UsersUserIdRoute from "@/app/api/users/[userId]/route";

export type KnownRoutes = {
  // Static Routes & Autocomplete Hints
  // /api/auth
  "/api/auth/login": typeof AuthLoginRoute;

  // /api/checkin
  "/api/checkin/verify": typeof CheckinVerifyRoute;

  // /api/extreme
  "/api/extreme/[orgId]/projects/[projectId]/tasks/[...catchall]": typeof ExtremeOrgIdProjectsProjectIdTasksCatchallRoute;
  "/api/extreme/complex-types": typeof ExtremeComplexTypesRoute;
  "/api/extreme/methods": typeof ExtremeMethodsRoute;

  // /api/orders
  "/api/orders/checkout": typeof OrdersCheckoutRoute;

  // /api/system
  "/api/system/health": typeof SystemHealthRoute;

  // /api/users
  "/api/users/[userId]": typeof UsersUserIdRoute;
};
// --- END GENERATED API REGISTRY ---

type Split<S extends string> = S extends `${infer Head}/${infer Tail}`
  ? [Head, ...Split<Tail>]
  : [S];

type MatchSegment<P extends string, K extends string> = K extends `[${string}]`
  ? P extends ""
    ? false
    : true
  : K extends P
    ? true
    : false;

type MatchSegments<P extends string[], K extends string[]> = K extends []
  ? P extends []
    ? true
    : false
  : K extends [`[...${string}]`]
    ? true
    : [P, K] extends [
          [infer PH extends string, ...infer PT extends string[]],
          [infer KH extends string, ...infer KT extends string[]],
        ]
      ? MatchSegment<PH, KH> extends true
        ? MatchSegments<PT, KT>
        : false
      : false;

type StripQuery<Path extends string> = Path extends `${infer Base}?${string}` ? Base : Path;

export type FindMatchingRoute<Path extends string> = {
  [K in keyof KnownRoutes & string]: MatchSegments<Split<StripQuery<Path>>, Split<K>> extends true
    ? K
    : never;
}[keyof KnownRoutes & string];

export type CheckPath<Path extends string> = Path extends ""
  ? keyof KnownRoutes
  : FindMatchingRoute<Path> extends never
    ? keyof KnownRoutes
    : Path;