// --- BEGIN GENERATED API REGISTRY ---
// This section is auto-generated by scripts/update-api-registry.mjs


export type KnownRoutes = {
  // Static Routes & Autocomplete Hints

};
// --- END GENERATED API REGISTRY ---
type Split<S extends string> = S extends `${infer Head}/${infer Tail}` ? [Head, ...Split<Tail>] : [S];

type MatchSegments<P extends string[], K extends string[]> = 
  K extends [] ? (P extends [] ? true : false) :
  K extends [`[...${string}]`] ? true :
  K extends [infer KHead extends string, ...infer KTail extends string[]] ? (
    P extends [infer PHead extends string, ...infer PTail extends string[]] ? (
      KHead extends `[${string}]` ? (PHead extends "" ? false : MatchSegments<PTail, KTail>) :
      KHead extends PHead ? MatchSegments<PTail, KTail> :
      false
    ) : false
  ) : false;

type StripQuery<Path extends string> = Path extends `${infer Base}?${string}` ? Base : Path;

export type FindMatchingRoute<Path extends string> = {
  [K in keyof KnownRoutes & string]: MatchSegments<Split<StripQuery<Path>>, Split<K>> extends true ? K : never
}[keyof KnownRoutes & string];

export type CheckPath<Path extends string> = 
  Path extends "" ? keyof KnownRoutes :
  FindMatchingRoute<Path> extends never ? `Error: Route '${Path}' is invalid or does not exist` : Path;